### PR TITLE
Added JSON reporter

### PR DESCRIPTION
**Pull request by romanblanco**
added option to output linter results in JSON format

@whoward could you check these changes please? :smile:

### CODE REVIEW

**Comment by whoward** [comment]
Hi @romanblanco
Thanks for the PR! I'm afraid I have a few requests to make before I merge this however:

1. Please look into the test suite, it's currently failing and needs to be fixed
2. Can we re-architect this to have a separate class for the JSON functionality?  Use the option parser to determine which class should be used but have both respond to the same methods so you can leverage duck typing.
3. `Object#to_json` isn't defined unless you have the `activesupport` gem, instead of using `obj.to_json` can you instead use `JSON.dump(obj)`?  This will probably break 1.8.7 support but these days I'm perfectly fine with that.

**Comment by romanblanco** [comment]
@whoward thanks for review, I'll work on that

**Comment by romanblanco** [comment]
@whoward After a long time I've finally updated my PR, but I'm having some issues with git and can't get it work. I'll be trying to fix that for a while, but I'm thinking about closing this PR and create a new one if I won't be able to figure this out.

**Comment by whoward** [comment]
a minor issue with the travis build but its easy enough to fix - merging

thanks!

**Comment by whoward** [comment]
pushed jslint-v8 v1.1.3 which includes these changes

**Comment by romanblanco** [comment]
@whoward thanks :+1:

**Pull request merged**
